# Generated by Django 3.1.8 on 2021-05-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inductionquizzes', '0002_auto_20210501_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inductionquizzes',
            old_name='questions',
            new_name='data',
        ),
    ]
