# Generated by Django 3.0.11 on 2021-04-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0003_auto_20210427_1500"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscontrolleddevice",
            name="secret_key",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Secret Key of device",
            ),
        ),
    ]
