---
# Common / default settings for all environments

# Short name for organization, used to name/tag things
org: gctechspace

# Globally unique name for organization, used for things like S3 buckets
org_unique: gctechspace

# Name of the app
app_name: membermatters

# Region to build in
# aws ec2 describe-regions
aws_region: ap-southeast-2

# Availiability zones
# aws ec2 describe-availability-zones --region ap-southeast-2
availability_zones: ["ap-southeast-2a", "ap-southeast-2b"]

# Whether KMS is available (not supported in China)
has_kms: true
